version: '2'
services:
    bookviewer-app:
        image: bookviewer
        external_links:
            - bookviewer-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=BookViewer
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bookviewer-mongodb:
        extends:
            file: mongodb.yml
            service: bookviewer-mongodb
